jodconverter:
  local:
    enabled: true

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true

spring:
  application:
    name: libreoffice-service

springdoc:
  api-docs:
    groups:
      enabled: true
  packages-to-scan: eu.henok.document.converter

logging:
  file:
    name: logs/libreoffice-service.log
  level:
    root: info
    com.sipgate.unitaccountingservice: debug